version: 2.1
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - push build:
          requires:
            - build
executors:
  hugo-executor:
    docker:
      - image: cibuilds/hugo:latest
jobs:
  build:
    executor: hugo-executor
    steps:
      - checkout

      - run:
          name: Update theme
          command: git submodule update --init --recursive

      - run:
          name: Build Hugo site
          command: hugo --destination=workspace/public

      # Persist the 'build' directory to the workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - public
  push build:
    executor: hugo-executor
    steps:
      - attach_workspace:
        at: workspace

      - run:
          name: Push build folder to GitHub
          command: |
            # Configure Git identity (replace <GitHubUsername> with your actual username)
            git config --global user.name "Jihhel"
            git config --global user.email "jihhel@users.noreply.github.com"

            # Clone the repository (replace <your-repo-name> with your actual repository URL)
            git clone --branch deploy --depth 1 https://jihhel:${GITHUB_TOKEN}@github.com/jihhel/bcdlv_website.git deployment

            # Copy the 'public' directory to the deployment folder
            cp -R workspace/public deployment

            # Navigate to the deployment folder
            cd deployment

            # Commit and push changes
            git add .
            git commit -m "Auto generated from ${CIRCLE_SHA1}"
            git push