name: Deploy to Kinsta in production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      HUGO_VERSION: 0.127.0

    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          
      - uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          TZ: Europe/Paris
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"          

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout to deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy-dev
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: public
          path: public
      - name: Push artifact
        run: |
          git config --global user.name "${{ github.event.head_commit.author.name }}"
          git config --global user.email "${{ github.event.head_commit.author.email }}"
          git add -f public
          git commit -am "Commit new artifact from commit ${{ github.event.head_commit.id }}"
          git push